name: Build and Deploy OficinaMVC to Production

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore, Build, and Publish
      run: dotnet publish ./OficinaMVC/OficinaMVC.csproj --configuration Release -o ./publish

    - name: Deploy to MonsterASP.net using Publish Profile
      uses: microsoft/webapps-deploy@v2
      with:
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        package: './publish'